src/br/com/softal/base/bean/AbstractManegedBean.java
package br.com.softal.base.bean;

import java.io.Serializable;
import java.util.List;

import javax.faces.context.FacesContext;

import br.com.softal.base.message.MessagesWeb;
import br.com.softal.base.model.Entity;
import br.com.softal.base.model.usuario.Usuario;
import br.com.softal.base.service.DefaultServiceImpl;
import br.com.softal.base.service.ServiceException;
import br.com.softal.loteca.LtcServiceLocator;
import br.com.softal.loteca.model.loteca.Loteca;
import br.com.softal.loteca.service.LotecaService;
import br.com.softal.loteca.sets.SpringFactory;
import br.com.softal.loteca.util.Constantes;

@SuppressWarnings("serial")
public abstract class AbstractManegedBean<E extends Entity> implements Serializable {
	
	//protected Logger logger = Logger.getLogger(getEntity().getClass().getName());  
	
	private MessagesWeb messages;
	private DefaultServiceImpl defaultService;
	private E entity;
	private List<E> rows;
	
	protected String getContext() {
		return FacesContext.getCurrentInstance().getExternalContext().getRequestContextPath();
	}

	public AbstractManegedBean() {
		initializeEntity();
		messages = new MessagesWeb();
		defaultService = (DefaultServiceImpl) SpringFactory.getInstance().getBean("defaultService"); 
	}
	
	public Loteca getLotecaativa() throws ServiceException {
		if (FacesContext.getCurrentInstance().getExternalContext().getSessionMap().containsKey(Constantes.LOTECA_ATIVA)) {
			return (Loteca) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get(Constantes.LOTECA_ATIVA);
		} else {
			try {
				Loteca loteca =  this.getLotecaService().findLotecaAtiva();
				FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put(Constantes.LOTECA_ATIVA, loteca);
				return loteca;
			} catch (Exception e) {
				throw new ServiceException(e);
			}
		}
	}


	public Usuario getUsuariologado() {
		return (Usuario) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get(Constantes.USUARIO_LOGADO);
	}

	public DefaultServiceImpl getDefaultService() {
		return defaultService;
	}
 
	public void setDefaultService(DefaultServiceImpl defaultService) {
		this.defaultService = defaultService;
	}
	
	public E getEntity() {
		return entity;
	}

	public void setEntity(E entity) {
		this.entity = entity;
	}

	public List<E> getRows() {
		return rows;
	}

	public void setRows(List<E> rows) {
		this.rows = rows;
	}
	
	public Integer getRowscount() {
		return getRows().size();
	}
	
	public void save() {
		defaultService.save(getEntity());
	}
	public void update() {
		defaultService.update(getEntity());
	}

	public void delete() {
		defaultService.delete(getEntity());
	}

	@SuppressWarnings("unchecked")
	public void findAll(E entity) {
		this.setRows( (List<E>) defaultService.findAll(entity) );
	}
	
	@SuppressWarnings("unchecked")
	public void findAll() {
		try {
			Entity x = (Entity) Class.forName(getEntity().getClass().getName()).newInstance();
			this.setRows( (List<E>) defaultService.findAll( x ) );
		} catch (InstantiationException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
	}
	

	public MessagesWeb getMessages() {
		return messages;
	}
	
	protected LotecaService getLotecaService() {
		return LtcServiceLocator.getInstance().getLotecaService();
	}

	protected abstract void initializeEntity();

}

src/br/com/softal/loteca/model/lotecausuario/HbnLotecausuarioDAO.java
package br.com.softal.loteca.model.lotecausuario;

import java.util.ArrayList;
import java.util.List;

import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import br.com.softal.base.dao.DaoException;
import br.com.softal.base.dao.GenericDAOImpl;
import br.com.softal.base.model.usuario.Usuario;
import br.com.softal.loteca.util.Constantes;
import br.com.softal.loteca.util.Enuns.SituacaoLoteca;

public class HbnLotecausuarioDAO extends GenericDAOImpl<Lotecausuario> implements LotecausuarioDAO {
	
	@SuppressWarnings("unchecked")
	@Override
	public List<Lotecausuario> findAllLotecausuarioByLoteca(long cdLoteca) {
		String hql =	"FROM Lotecausuario x " +
			    		"where x.loteca.cdLoteca = " + cdLoteca ;
		return getHibernateTemplate().find(hql);
	}
	
	@Override
	public List<Lotecausuario> findAllLotecausuarioAtivoByLoteca(long cdLoteca) {
		String hql =	"FROM Lotecausuario x " +
				"where x.flAtivo = 1 " + 
				"and x.loteca.cdLoteca = " + cdLoteca ;
		return getHibernateTemplate().find(hql);
	}
	
	public Lotecausuario findLotecausuarioAtivo(Usuario usuario) {
		List<Lotecausuario> lista = new ArrayList<Lotecausuario>();
		StringBuilder hql = new StringBuilder();
		hql.append("SELECT lu ");
		hql.append("FROM Lotecausuario lu ");
		hql.append("LEFT JOIN FETCH lu.loteca lo ");
		hql.append("LEFT JOIN FETCH lu.usuario us ");
		hql.append("WHERE us.cdUsuario = :cdUsuario ");
		hql.append("AND lu.flAtivo = 1");
		hql.append("AND lo.tpSituacao = :tpSituacao");		
		Session session = getHibernateTemplate().getSessionFactory().openSession();
		Transaction tx = session.beginTransaction();
		try {
			Query query = session.createQuery( hql.toString() );
			query.setLong("cdUsuario", usuario.getCdUsuario() );
			query.setLong("tpSituacao", SituacaoLoteca.ANDAMENTO.longValue() ); //-- Constantes.DATA_SITUACAO_EM_ANDAMENTO
			lista = query.list();
			tx.commit();
		} catch (Exception e) {
			tx.rollback();
			e.printStackTrace();
		} finally {
			session.close();
		}
		return (lista.size() > 0) ? lista.get(0) : null;
	}
	
	public Lotecausuario findLotecausuarioInscricao(Usuario usuario) {
		List<Lotecausuario> lista = new ArrayList<Lotecausuario>();
		StringBuilder hql = new StringBuilder();
		hql.append("SELECT lu ");
		hql.append("FROM Lotecausuario lu ");
		hql.append("LEFT JOIN FETCH lu.loteca lo ");
		hql.append("LEFT JOIN FETCH lu.usuario us ");
		hql.append("WHERE us.cdUsuario = :cdUsuario ");
		hql.append("AND lo.tpSituacao = :tpSituacao");		
		Session session = getHibernateTemplate().getSessionFactory().openSession();
		Transaction tx = session.beginTransaction();
		try {
			Query query = session.createQuery( hql.toString() );
			query.setLong("cdUsuario", usuario.getCdUsuario() );
			query.setLong("tpSituacao", SituacaoLoteca.CADASTRAMENTO.longValue() ); //-- Constantes.DATA_SITUACAO_CADASTRAMENTO
			lista = query.list();
			tx.commit();
		} catch (Exception e) {
			tx.rollback();
			e.printStackTrace();
		} finally {
			session.close();
		}
		return (lista.size() > 0) ? lista.get(0) : null;
	}
	
	@Override
	public Lotecausuario findLotecausuario(Lotecausuario lotecausuario)
			throws DaoException {
		List<Lotecausuario> lista = new ArrayList<Lotecausuario>();
		StringBuilder hql = new StringBuilder();
		hql.append("SELECT lu ");
		hql.append("FROM Lotecausuario lu ");
		hql.append("LEFT JOIN FETCH lu.loteca lo ");
		hql.append("LEFT JOIN FETCH lu.usuario us ");
		hql.append("WHERE us.cdUsuario = :cdUsuario ");
		hql.append("AND lo.cdLoteca = :cdLoteca");		
		Session session = getHibernateTemplate().getSessionFactory().openSession();
		Transaction tx = session.beginTransaction();
		try {
			Query query = session.createQuery( hql.toString() );
			query.setLong("cdUsuario", lotecausuario.getUsuario().getCdUsuario() );
			query.setLong("cdLoteca", lotecausuario.getLoteca().getCdLoteca() );
			lista = query.list();
			tx.commit();
		} catch (Exception e) {
			tx.rollback();
			e.printStackTrace();
		} finally {
			session.close();
		}
		return (lista.size() > 0) ? lista.get(0) : null;
	}
}

src/br/com/softal/loteca/model/lotecausuario/Lotecausuario.java
package br.com.softal.loteca.model.lotecausuario;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import br.com.softal.base.model.Entity;
import br.com.softal.base.model.usuario.Usuario;
import br.com.softal.loteca.model.clubeusuario.Clubeusuario;
import br.com.softal.loteca.model.loteca.Loteca;

@SuppressWarnings("serial")
@javax.persistence.Entity
@Table(name = "eltclotecausuario")
public class Lotecausuario extends Entity {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "nuseqlotecausuario")
	//@OneToMany(mappedBy = "lotecausuario")
	private long nuSeqlotecausuario;

	@Column(name = "flativo")
	private Long flAtivo;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="cdusuario", insertable=true, updatable=true)
	@Fetch(FetchMode.JOIN)
	//@Cascade(CascadeType.SAVE_UPDATE)
	private Usuario usuario;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="cdloteca", insertable=true, updatable=true)
	@Fetch(FetchMode.JOIN)
	//@Cascade(CascadeType.SAVE_UPDATE)
	private Loteca loteca;
	
	@OneToMany(mappedBy="lotecausuario", fetch=FetchType.LAZY)
	//@Cascade(CascadeType.ALL)
	private List<Clubeusuario> clubeusuarios;

	public Lotecausuario() {
		super();
	}
	
	public Lotecausuario(long nuSeqlotecausuario, Long flAtivo,
			Long  cdUsuario, Long cdLoteca) {
		this();
		this.inicializaRelacionamentos();
		this.nuSeqlotecausuario = nuSeqlotecausuario;
		this.flAtivo = flAtivo;
		getUsuario().setCdUsuario(cdUsuario);
		getLoteca().setCdLoteca(cdLoteca);
	}


	public long getNuSeqlotecausuario() {
		return nuSeqlotecausuario;
	}

	public void setNuSeqlotecausuario(long nuSeqlotecausuario) {
		this.nuSeqlotecausuario = nuSeqlotecausuario;
	}

	public Long getFlAtivo() {
		return flAtivo;
	}

	public void setFlAtivo(Long flAtivo) {
		this.flAtivo = flAtivo;
	}
	
	public Boolean getBlAtivo() {
		return flAtivo != null && flAtivo == 1l;
	}
	
	public void setBlAtivo(Boolean blAtivo) {
		this.flAtivo = (blAtivo == null) ? 0l : (blAtivo ?  1l : 0l);
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Loteca getLoteca() {
		return loteca;
	}

	public void setLoteca(Loteca loteca) {
		this.loteca = loteca;
	}

	public List<Clubeusuario> getClubeusuarios() {
		return clubeusuarios;
	}

	public void setClubeusuarios(List<Clubeusuario> clubeusuarios) {
		this.clubeusuarios = clubeusuarios;
	}
	
	@Override
	public void inicializaRelacionamentos() {
		setUsuario(new Usuario());
		setLoteca(new Loteca());
		setClubeusuarios(new ArrayList<Clubeusuario>());
	}
	
}

src/br/com/softal/loteca/model/lotecausuario/LotecausuarioDAO.java
package br.com.softal.loteca.model.lotecausuario;

import java.util.List;

import br.com.softal.base.dao.DaoException;
import br.com.softal.base.dao.GenericDAO;
import br.com.softal.base.model.usuario.Usuario;

public interface LotecausuarioDAO extends GenericDAO<Lotecausuario> {
	
	List<Lotecausuario> findAllLotecausuarioByLoteca(long cdLoteca) throws DaoException;
	Lotecausuario findLotecausuarioAtivo(Usuario usuario) throws DaoException;
	Lotecausuario findLotecausuarioInscricao(Usuario usuario) throws DaoException;
	Lotecausuario findLotecausuario(Lotecausuario lotecausuario) throws DaoException;
	List<Lotecausuario> findAllLotecausuarioAtivoByLoteca(long cdLoteca) throws DaoException;

}

WebContent/pages/adm/lotecausuario/eltcCadLotecausuario.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<ui:composition
	template="/templates/template.xhtml">

	<ui:define name="context">
		<h:form>
			<h:inputHidden value="#{lotecausuarioBean.entity.status}"  />
			<h:inputHidden value="#{lotecausuarioBean.entity.nuSeqlotecausuario}"  />
			<p:messages showDetail="true" showSummary="false" />
			<p:panel header="#{msg.lotecausuario_titulo_usuario_loteca}" >
				<h:panelGrid columns="2" style="width:100%" columnClasses="headerColumn alignRight bold">
				
					<h:outputLabel value="#{msg.lotecausuario_cdloteca}:" />
					<h:selectOneMenu value="#{lotecausuarioBean.entity.loteca.cdLoteca}" id="cdLoteca" style="width: 100%" 
						required="true" requiredMessage="#{msg.lotecausuario_cdloteca_requirido}"
						disabled="#{lotecausuarioBean.entity.status ne 'I'}">
						<f:selectItem itemLabel="#{msg.selectonemenu_selecione}" itemValue="" />
						<f:selectItems value="#{lotecausuarioBean.lotecas}" var="lot" itemLabel="#{lot.deLoteca}" itemValue="#{lot.cdLoteca}" />
					</h:selectOneMenu>
					
					<h:outputLabel value="#{msg.lotecausuario_cdusuario}:" />
					<h:selectOneMenu value="#{lotecausuarioBean.entity.usuario.cdUsuario}" id="cdUsuario" style="width: 100%" 
						required="true" requiredMessage="#{msg.lotecausuario_cdusuario_requirido}"
						disabled="#{lotecausuarioBean.entity.status ne 'I'}">
						<f:selectItem itemLabel="#{msg.selectonemenu_selecione}" itemValue="" />
						<f:selectItems value="#{lotecausuarioBean.usuarios}" var="usu" itemLabel="#{usu.nmUsuario}" itemValue="#{usu.cdUsuario}" />
					</h:selectOneMenu>
					
					<h:outputLabel value="" />
					<p:selectBooleanCheckbox value="#{lotecausuarioBean.entity.blAtivo}" itemLabel="#{msg.lotecausuario_flativo}" 
						styleClass="bold" label="#{msg.lotecausuario_flativo}" />
				</h:panelGrid>
				
				<f:facet name="footer">
					<p:commandButton value="#{msg.button_save}" action="#{lotecausuarioBean.save}" ajax="false" />
					<p:commandButton value="#{msg.button_novo}" action="#{lotecausuarioBean.adicionar}" ajax="false" immediate="true"/>
					<p:commandButton value="#{msg.button_voltar}" action="eltcConLotecausuario" ajax="false" immediate="true"/>
				</f:facet>	
			</p:panel>
			<br/>
			<p:panel header="#{msg.lotecausuario_clubes_usuario}" rendered="#{lotecausuarioBean.entity.status ne 'I'}">
				<p:orderList value="#{lotecausuarioBean.entity.clubeusuarios}" var="clubeusuario" 
					iconOnly="true" effect="highlight" 
					itemValue="#{clubeusuario}" converter="clubeusuarioConverter" 
					controlsLocation="left" id="customList" rendered="#{sistemaBean.lotecaativa.tpSituacao eq 1}">
				         <p:column style="width:100%;"> 
				         	#{clubeusuario.nuPosicao} - #{clubeusuario.clube.nmClube}
				        </p:column>
			    </p:orderList>	
			    
				<h:panelGrid columns="2" style="width:100%" >
					<p:orderList value="#{lotecausuarioBean.clubesclassificados}" var="clubeclass" 
						rendered="#{sistemaBean.lotecaativa.tpSituacao ne 1}"
						converter="clubeusuarioConverter" controlsLocation="none" disabled="true">
					         <p:column style="width:100%;"> 
					         	#{clubeclass.nuPosicao} - #{clubeclass.clube.nmClube}
					        </p:column>
			   		</p:orderList>	
			   		
					<p:orderList value="#{lotecausuarioBean.clubesrebaixados}" var="clubereba" 
						rendered="#{sistemaBean.lotecaativa.tpSituacao ne 1}"
						converter="clubeusuarioConverter" controlsLocation="none" disabled="true">
					         <p:column style="width:100%;"> 
					         	#{clubereba.nuPosicao} - #{clubereba.clube.nmClube}
					        </p:column>
			   		</p:orderList>	
				</h:panelGrid>			    	
            </p:panel>
		</h:form>
	</ui:define>
</ui:composition>
</html>

WebContent/pages/adm/lotecausuario/eltcConLotecausuario.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<ui:composition
	template="/templates/template.xhtml">

	<ui:define name="context">
			<h:form>
				<p:messages showDetail="true" showSummary="false" />
				<p:panelGrid columns="2" style="width:100%" columnClasses="headerColumn alignRight bold">
					<f:facet name="header">
						#{msg.lotecausuario_consultar}
					</f:facet>
					<h:outputLabel value="#{msg.clube_cdloteca}:" for="cdLoteca" />
					<h:selectOneMenu value="#{lotecausuarioBean.cdLoteca}" id="cdLoteca" style="width: 100%" 
						required="false" requiredMessage="#{msg.lotecausuario_cdloteca_requirido}" 
						valueChangeListener="#{lotecausuarioBean.carregaUsuariosloteca}"
						onchange="submit()" immediate="true">
						<f:selectItem itemLabel="#{msg.selectonemenu_selecione}" itemValue="" />
						<f:selectItems value="#{lotecausuarioBean.lotecas}" var="lot" itemLabel="#{lot.deLoteca}" itemValue="#{lot.cdLoteca}" />
					</h:selectOneMenu>
					<f:facet name="footer">
						<p:commandButton value="#{msg.button_novo}"
							action="#{lotecausuarioBean.adicionar}" ajax="false" />
					</f:facet>
				</p:panelGrid>
				<br/>			
			
				<p:dataTable id="lotecausuarios" var="row" value="#{lotecausuarioBean.rows}"
					rowKey="#{row.nuSeqlotecausuario}" selection="#{lotecausuarioBean.entity}"
					selectionMode="single" emptyMessage="#{msg.warning_nenhum_registro_encontrado}">
					<p:column headerText="#{msg.lotecausuario_cdusuario}">
						<h:outputText value="#{row.usuario.nmUsuario}" />
					</p:column>
					<p:column headerText="#{msg.lotecausuario_flativo}" style="width:80px;text-align:center;">
						<p:selectBooleanCheckbox value="#{row.blAtivo}" disabled="true" >
						</p:selectBooleanCheckbox>
					</p:column>
					<p:column style="width:15px">
						<p:commandButton id="selectButton" icon="ui-icon-search" title="Editar" action="#{lotecausuarioBean.editar}" ajax="false">
							<f:setPropertyActionListener value="#{row}" target="#{lotecausuarioBean.entity}" />
						</p:commandButton>
					</p:column>
				</p:dataTable>
				<p:messages showDetail="true" showSummary="false" />
			</h:form>
	</ui:define>
</ui:composition>
</html>