src/br/com/softal/loteca/dto/ComparacaoDto.java
package br.com.softal.loteca.dto;

import java.util.List;

public class ComparacaoDto {

	private String nmUsuario;
	private Long cdJogo;
	private String deJogo;
	private Long tpResultadofinal;
	private Long tpJogo;
	private Long flColuna1;
	private Long flEmpate;
	private Long flColuna2;

	private List<ComparacaoDto> jogos;
	
	
	public ComparacaoDto() {
	}
	
	public ComparacaoDto(Long cdJogo, String deJogo, Long tpResultadofinal) {
		this();
		this.cdJogo = cdJogo;
		this.deJogo = deJogo;
		this.tpResultadofinal = tpResultadofinal;
	}
	
	public ComparacaoDto(String nmUsuario, Long tpJogo, Long flColuna1, Long flEmpate, Long flColuna2) {
		this();
		this.nmUsuario = nmUsuario;
		this.tpJogo = tpJogo;
		this.flColuna1 = flColuna1;
		this.flEmpate = flEmpate;
		this.flColuna2 = flColuna2;
	}

	public String getNmUsuario() {
		return nmUsuario;
	}

	public void setNmUsuario(String nmUsuario) {
		this.nmUsuario = nmUsuario;
	}

	public Long getCdJogo() {
		return cdJogo;
	}

	public void setCdJogo(Long cdJogo) {
		this.cdJogo = cdJogo;
	}

	public String getDeJogo() {
		return deJogo;
	}

	public void setDeJogo(String deJogo) {
		this.deJogo = deJogo;
	}

	public Long getTpResultadofinal() {
		return tpResultadofinal;
	}

	public void setTpResultadofinal(Long tpResultadofinal) {
		this.tpResultadofinal = tpResultadofinal;
	}

	public Long getFlColuna1() {
		return flColuna1;
	}

	public void setFlColuna1(Long flColuna1) {
		this.flColuna1 = flColuna1;
	}

	public Long getFlEmpate() {
		return flEmpate;
	}

	public void setFlEmpate(Long flEmpate) {
		this.flEmpate = flEmpate;
	}

	public Long getFlColuna2() {
		return flColuna2;
	}

	public void setFlColuna2(Long flColuna2) {
		this.flColuna2 = flColuna2;
	}

	public List<ComparacaoDto> getJogos() {
		return jogos;
	}

	public void setJogos(List<ComparacaoDto> jogos) {
		this.jogos = jogos;
	}

	public Long getTpJogo() {
		return tpJogo;
	}

	public void setTpJogo(Long tpJogo) {
		this.tpJogo = tpJogo;
	}
	
	public String getTpResultadofinaldesc() {
		if (getTpResultadofinal() == 0) {
			return "Empate";
		} else if (getTpResultadofinal() == 1) {
			return "Coluna 1";
		} 
		return "Coluna 2";
	}
	

}

src/br/com/softal/loteca/comparacao/ComparacaoBean.java
package br.com.softal.loteca.comparacao;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import br.com.softal.base.bean.AbstractManegedBean;
import br.com.softal.base.model.usuario.Usuario;
import br.com.softal.loteca.dto.ComparacaoDto;
import br.com.softal.loteca.model.data.Data;
import br.com.softal.loteca.model.jogousuario.Jogousuario;
import br.com.softal.loteca.model.loteca.Loteca;
import br.com.softal.loteca.model.lotecausuario.Lotecausuario;
import br.com.softal.loteca.model.usuariodata.AproveitamentoDTO;
import br.com.softal.loteca.model.usuariodata.Usuariodata;

@SuppressWarnings("serial")
@ManagedBean(name="comparacaoBean")
@RequestScoped
public class ComparacaoBean extends AbstractManegedBean implements Serializable {
	
	private Long cdUsuario;
	private Long cdData;
	private String deResultado;
	
	private List<ComparacaoDto> jogos;
	private List<Lotecausuario> lotecausuarios;
	private List<Data> datas;
	private Usuario usuariologado;
	private Loteca loteca;
	
	public String getDeResultado() {
		return deResultado;
	}
	
	public Long getCdUsuario() {
		return cdUsuario;
	}

	public void setCdUsuario(Long cdUsuario) {
		this.cdUsuario = cdUsuario;
	}
	
	public List<Lotecausuario> getLotecausuarios() {
		return lotecausuarios;
	}
	
	public List<Data> getDatas() {
		return datas;
	}
	
	public Long getCdData() {
		return cdData;
	}

	public void setCdData(Long cdData) {
		this.cdData = cdData;
	}
	
	private void ordenaLotecaUsuarios() {
		Collections.sort(lotecausuarios, new Comparator<Lotecausuario>() {
			@Override
			public int compare(Lotecausuario o1, Lotecausuario o2) {
				return o1.getUsuario().getNmUsuario().compareTo(o2.getUsuario().getNmUsuario());
			}
		});
	}
	
	private void removeUsuarioLogadodaLista() {
		for (Lotecausuario lu : this.lotecausuarios) {
			if (lu.getUsuario().getCdUsuario().equals(this.usuariologado.getCdUsuario())) {
				this.lotecausuarios.remove(lu);
				break;
			}
		}
	}
	
	public List<ComparacaoDto> getJogos() {
		return jogos;
	}
	
	private void carregaResultados(Data data, Usuario usuariologado, Usuario adversario) {
		try {
			List<Usuariodata> datas = super.getLotecaService().findAllUsuariodata(this.getLotecaativa(), data);
			Map<Long, Usuariodata> mapUsuarios = new HashMap<Long, Usuariodata>();
			for (Usuariodata aprov : datas) {
				mapUsuarios.put( aprov.getLotecausuario().getUsuario().getCdUsuario() , aprov);
			}
			
			Usuariodata usuLogado = mapUsuarios.get( usuariologado.getCdUsuario() );
			Usuariodata usuAdver = mapUsuarios.get( adversario.getCdUsuario() );
			
			this.deResultado = usuariologado.getNmUsuario() + "  " + usuLogado.getNuPontoscartao() + " x " + usuAdver.getNuPontoscartao() + "  " + adversario.getNmUsuario();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	@PostConstruct
	public void init() {
		try {
			usuariologado = super.getUsuariologado();
			loteca = super.getLotecaativa();
			lotecausuarios = super.getLotecaService().findAllLotecausuarioAtivoByLoteca(loteca);
			datas = super.getLotecaService().findAllDatasEncerradas(loteca);
			jogos = new ArrayList<ComparacaoDto>();
			
			removeUsuarioLogadodaLista();
			this.ordenaLotecaUsuarios();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	@Override
	protected void initializeEntity() {
	}
	
	public String abrirComparacaoApostas() {
		
		return "/pages/user/comparacao/eltcConComparacaoApostas.xhtml";
	}
	
	public String carregaJogousuario() {
		try {
			Data data = super.getLotecaService().findData(this.cdData);
			
			
			Lotecausuario lotecausuariologado = super.getLotecaService().findLotecausuarioAtivo(usuariologado);
			List<Jogousuario> jogosusuariologado = super.getLotecaService().findAllJogoUsuario(data, lotecausuariologado);
			Map<Long, Jogousuario> mapUsuarioLogado = new HashMap<Long, Jogousuario>();
			for (Jogousuario jo : jogosusuariologado) {
				mapUsuarioLogado.put(jo.getJogo().getCdJogo(), jo);
			}
			
			Usuario usuario = new Usuario();
			usuario.setCdUsuario(this.cdUsuario);
			Lotecausuario lotecausuario = super.getLotecaService().findLotecausuarioAtivo(usuario);
			List<Jogousuario> jogosusuario = super.getLotecaService().findAllJogoUsuario(data, lotecausuario);
			Map<Long, Jogousuario> mapAdversario = new HashMap<Long, Jogousuario>();
			for (Jogousuario jo : jogosusuario) {
				mapAdversario.put(jo.getJogo().getCdJogo(), jo);
			}
			
			jogos.clear();
			for (long l = 1; l<=14;l++) {
				Jogousuario jogoUsuarioLogado = mapUsuarioLogado.get( l );
				Jogousuario jogoAdversario = mapAdversario.get( l );
				ComparacaoDto dtoUsuarioLogado = new ComparacaoDto( usuariologado.getNmUsuario(), jogoUsuarioLogado.getTpJogo(), jogoUsuarioLogado.getFlColuna1(), jogoUsuarioLogado.getFlEmpate(), jogoUsuarioLogado.getFlColuna2());
				ComparacaoDto dtoAdversario = new ComparacaoDto( lotecausuario.getUsuario().getNmUsuario(), jogoAdversario.getTpJogo(), jogoAdversario.getFlColuna1(), jogoAdversario.getFlEmpate(), jogoAdversario.getFlColuna2());
				
				ComparacaoDto dto = new ComparacaoDto(l, jogoUsuarioLogado.getJogo().getDeJogo(), jogoUsuarioLogado.getJogo().getTpResultadofinal());
				dto.setJogos(new ArrayList<ComparacaoDto>());
				dto.getJogos().add(dtoUsuarioLogado);
				dto.getJogos().add(dtoAdversario);
				
				jogos.add(dto);
			}
			
			this.carregaResultados( data, this.usuariologado, lotecausuario.getUsuario());
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return "/pages/user/comparacao/eltcConComparacaoApostas.xhtml";
	}

}

WebContent/pages/user/comparacao/eltcConComparacaoApostas.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<ui:composition
	template="/templates/template.xhtml">

	<ui:define name="context">
		<h:form id="comparacaoForm">
			<p:messages showDetail="true" showSummary="false" />
			
			<p:panelGrid columns="2" style="width:100%" columnClasses="headerColumn alignRight bold">
				<f:facet name="header">
					#{msg.comparacao_titulo}
				</f:facet>
				<h:outputLabel value="#{msg.comparacao_concurso}:" for="cddata" />
				<h:selectOneMenu value="#{comparacaoBean.cdData}" id="cddata" style="width: 100%" 
					required="true" requiredMessage="#{msg.comparacao_concurso_requirido}"  >
					<f:selectItem itemLabel="#{msg.selectonemenu_selecione}" itemValue="" />
					<f:selectItems value="#{comparacaoBean.datas}" var="data" itemLabel="#{data.deObservacao}" itemValue="#{data.cdData}" />
				</h:selectOneMenu>
				
				<h:outputLabel value="#{msg.comparacao_adversario}:" for="cdusuario" />
				<h:selectOneMenu value="#{comparacaoBean.cdUsuario}" id="cdusuario" style="width: 100%" 
					required="true" requiredMessage="#{msg.comparacao_adversario_requirido}"  >
					<f:selectItem itemLabel="#{msg.selectonemenu_selecione}" itemValue="" />
					<f:selectItems value="#{comparacaoBean.lotecausuarios}" var="usu" itemLabel="#{usu.usuario.nmUsuario}" itemValue="#{usu.usuario.cdUsuario}" />
				</h:selectOneMenu>
				<f:facet name="footer">
					<p:commandButton value="#{msg.button_comparar}"
						action="#{comparacaoBean.carregaJogousuario}" ajax="false" />
				</f:facet>
			</p:panelGrid>
			<br/>
			
			<p:panel rendered="#{not empty comparacaoBean.deResultado}">
				<div style="text-align: center;">
					<p:outputLabel value="#{comparacaoBean.deResultado}" 
						style="color: red;font-size: 20px"/>
				</div>
			</p:panel>
			<br />
			
			<p:accordionPanel  value="#{comparacaoBean.jogos}" var="row" >
				<p:tab title="#{row.cdJogo} - #{row.deJogo} (Resultado: #{row.tpResultadofinaldesc})" >
					<p:dataTable var="jogo" value="#{row.jogos}">  
						<p:column headerText="Jogadores">  
            				<h:outputText value="#{jogo.nmUsuario}" />  
       					</p:column>
       					 
						<p:column headerText="Coluna 1" style="width:50px;" 
							styleClass="alignCenter   
								#{row.tpResultadofinal eq 1 ? 'resultado' : ''}
								#{row.tpResultadofinal eq 1 and jogo.flColuna1 eq 1 ? 'acertoClass' : ''}
								#{jogo.tpJogo ne 1 and row.tpResultadofinal ne 1 and jogo.flColuna1 eq 1 ? 'erroClass' : ''}">
							<p:graphicImage url="/images/ok.png" rendered="#{row.tpResultadofinal eq 1 and jogo.flColuna1 eq 1}" width="20"/>
							<p:graphicImage url="/images/nok.png" rendered="#{row.tpResultadofinal ne 1 and jogo.flColuna1 eq 1}" width="20"/>
						</p:column>	 		
						
						<p:column headerText="Empate" style="width:50px;" 	
							styleClass="alignCenter   
								#{row.tpResultadofinal eq 0 ? 'resultado' : ''}
								#{row.tpResultadofinal eq 0 and jogo.flEmpate eq 1 ? 'acertoClass' : ''}
								#{jogo.tpJogo ne 1 and row.tpResultadofinal ne 0 and jogo.flEmpate eq 1 ? 'erroClass' : ''}">
							<p:graphicImage url="/images/ok.png" rendered="#{row.tpResultadofinal eq 0 and jogo.flEmpate eq 1}" width="20"/>
							<p:graphicImage url="/images/nok.png" rendered="#{row.tpResultadofinal ne 0 and jogo.flEmpate eq 1}" width="20"/>
						</p:column>			 
		       					 
		       			<p:column headerText="Coluna 2" style="width:50px;" 
							styleClass="alignCenter   
							#{row.tpResultadofinal eq 2 ? 'resultado' : ''}
							#{row.tpResultadofinal eq 2 and jogo.flColuna2 eq 1 ? 'acertoClass' : ''}
							#{row.tpJogo ne 1 and row.tpResultadofinal ne 2 and jogo.flColuna2 eq 1 ? 'erroClass' : ''}">
							<p:graphicImage url="/images/ok.png" rendered="#{row.tpResultadofinal eq 2 and jogo.flColuna2 eq 1}" width="20"/>
							<p:graphicImage url="/images/nok.png" rendered="#{row.tpResultadofinal ne 2 and jogo.flColuna2 eq 1}" width="20"/>
						</p:column>	 
       					 
					</p:dataTable>
				</p:tab>
			</p:accordionPanel>
			
			<br/>
			<table>
				<tr>
					<td class="resultado" style="border-width: 1px;border-style: solid;width: 20px;">&nbsp;</td>
					<td style="width: 50px">Resultado</td>
					<td class="" style="border-width: 1px;border-style: solid;width: 20px;"><p:graphicImage url="/images/ok.png" width="20"/></td>
					<td style=": 50px">Acerto</td>
					<td class="" style="border-width: 1px;border-style: solid;width: 20px;"><p:graphicImage url="/images/nok.png" width="20"/></td>
					<td style="width: 50px">Erro</td>
				</tr>
			</table>	
		
		</h:form>
	</ui:define>
</ui:composition>
</html>